Update patch set 1
Patch Set 1: Verified-1 Code-Review-1

FATAL EXCEPTION: main
Process: com.lineageos.settings.device, PID: 9079
java.lang.RuntimeException: Unable to instantiate service com.lineageos.settings.device.GrayTileService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
 at android.app.ActivityThread.handleCreateService(ActivityThread.java:3941)
 at android.app.ActivityThread.access$1500(ActivityThread.java:220)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1876)
 at android.os.Handler.dispatchMessage(Handler.java:107)
 at android.os.Looper.loop(Looper.java:214)
 at android.app.ActivityThread.main(ActivityThread.java:7361)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
 at android.content.ContextWrapper.getPackageName(ContextWrapper.java:145)
 at android.preference.PreferenceManager.getDefaultSharedPreferencesName(PreferenceManager.java:555)
 at android.preference.PreferenceManager.getDefaultSharedPreferences(PreferenceManager.java:545)
 at com.lineageos.settings.device.GrayTileService.<init>(GrayTileService.java:10)
 at java.lang.Class.newInstance(Native Method)
 at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
 at android.app.ActivityThread.handleCreateService(ActivityThread.java:3936)
 ... 8 more

Patch-set: 1
Reviewer: Gerrit User 273 <273@4c0b52a2-b090-4331-a190-b288d812d081>
Label: Code-Review=-1
Label: Verified=-1