Update patch set 1
Patch Set 1: Verified-1

It doesn't build. Need a help.
FAILED: /run/media/dmitry/1e8e1b30-189e-4254-8ae0-6408e61bf13c/carbon/out/target/product/mido/obj/SHARED_LIBRARIES/fakelogprint_intermediates/fakelogprint/fakelogprint.o
/bin/bash -c "PWD=/proc/self/cwd  prebuilts/clang/host/linux-x86/clang-r353983c1/bin/clang++ 	-I device/xiaomi/mido/include -I device/xiaomi/mido/libshims -I /run/media/dmitry/1e8e1b30-189e-4254-8ae0-6408e61bf13c/carbon/out/target/produ
ct/mido/obj/SHARED_LIBRARIES/fakelogprint_intermediates -I /run/media/dmitry/1e8e1b30-189e-4254-8ae0-6408e61bf13c/carbon/out/target/product/mido/gen/SHARED_LIBRARIES/fakelogprint_intermediates \$(cat /run/media/dmitry/1e8e1b30-189e-4254-8
ae0-6408e61bf13c/carbon/out/target/product/mido/obj/SHARED_LIBRARIES/fakelogprint_intermediates/import_includes)   -isystem /run/media/dmitry/1e8e1b30-189e-4254-8ae0-6408e61bf13c/carbon/out/target/product/mido/obj/include -c  -Werror=impl
icit-function-declaration -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -no-canonical-prefixes -DNDEBUG -UDEBUG -fno-exceptions -Wno-multichar -O2 -g -fno-strict-aliasing -fdebug-prefix-map=/proc/self/cwd= 
-D__compiler_offsetof=__builtin_offsetof -faddrsig -Wimplicit-fallthrough -Werror=int-conversion -Wno-reserved-id-macro -Wno-format-pedantic -Wno-unused-command-line-argument -fcolor-diagnostics -Wno-zero-as-null-pointer-constant -Wno-sig
n-compare -Wno-defaulted-function-deleted -Wno-inconsistent-missing-override -ffunction-sections -fdata-sections -fno-short-enums -funwind-tables -fstack-protector-strong -Wa,--noexecstack -D_FORTIFY_SOURCE=2 -Wstrict-aliasing=2 -Werror=r
eturn-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Werror=date-time -Werror=format-security -nostdlibinc -march=armv8-a  -target aarch64-linux-android -Bprebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/aa
rch64-linux-android/bin  -Wsign-promo -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -Wno-thread-safety-negative -Wno-gnu-include-next -fvisibility-inlines-hidden  -std=gnu++17   -fno-rtti -Wall -D__ANDROID_API__=29 -D__ANDROID_VNDK__ -fPIC -
D_USING_LIBCXX -DANDROID_STRICT   -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=address-of-temporary -Werror=return-type -Wno-tautological-constant-compare -Wno-tautological-type-limit-compare -Wno-tautological-unsigned-
enum-zero-compare -Wno-tautological-unsigned-zero-compare -Wno-c++98-compat-extra-semi -Wno-return-std-move-in-c++11  -MD -MF /run/media/dmitry/1e8e1b30-189e-4254-8ae0-6408e61bf13c/carbon/out/target/product/mido/obj/SHARED_LIBRARIES/fakel
ogprint_intermediates/fakelogprint/fakelogprint.d -o /run/media/dmitry/1e8e1b30-189e-4254-8ae0-6408e61bf13c/carbon/out/target/product/mido/obj/SHARED_LIBRARIES/fakelogprint_intermediates/fakelogprint/fakelogprint.o device/xiaomi/mido/libs
hims/fakelogprint/fakelogprint.cpp"
device/xiaomi/mido/libshims/fakelogprint/fakelogprint.cpp:1:10: fatal error: 'log/log_transport.h' file not found
#include <log/log_transport.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
[ 10% 511/4948] target thumb C++: fakelogprint_32 <= device/xiaomi/mido/libshims/fakelogprint/fakelogprint.cpp
FAILED: /run/media/dmitry/1e8e1b30-189e-4254-8ae0-6408e61bf13c/carbon/out/target/product/mido/obj_arm/SHARED_LIBRARIES/fakelogprint_intermediates/fakelogprint/fakelogprint.o
/bin/bash -c "PWD=/proc/self/cwd  prebuilts/clang/host/linux-x86/clang-r353983c1/bin/clang++ 	-I device/xiaomi/mido/include -I device/xiaomi/mido/libshims -I /run/media/dmitry/1e8e1b30-189e-4254-8ae0-6408e61bf13c/carbon/out/target/produ
ct/mido/obj_arm/SHARED_LIBRARIES/fakelogprint_intermediates -I /run/media/dmitry/1e8e1b30-189e-4254-8ae0-6408e61bf13c/carbon/out/target/product/mido/gen/SHARED_LIBRARIES/fakelogprint_intermediates \$(cat /run/media/dmitry/1e8e1b30-189e-42
54-8ae0-6408e61bf13c/carbon/out/target/product/mido/obj_arm/SHARED_LIBRARIES/fakelogprint_intermediates/import_includes)   -isystem /run/media/dmitry/1e8e1b30-189e-4254-8ae0-6408e61bf13c/carbon/out/target/product/mido/obj/include -c  -fom
it-frame-pointer -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -no-canonical-prefixes -DNDEBUG -UDEBUG -fno-exceptions -Wno-multichar -O2 -g -fno-strict-aliasing -fdebug-prefix-map=/proc/self/cwd= -D__compi
ler_offsetof=__builtin_offsetof -faddrsig -Wimplicit-fallthrough -Werror=int-conversion -Wno-reserved-id-macro -Wno-format-pedantic -Wno-unused-command-line-argument -fcolor-diagnostics -Wno-zero-as-null-pointer-constant -Wno-sign-compare
 -Wno-defaulted-function-deleted -Wno-inconsistent-missing-override -ffunction-sections -fdata-sections -fno-short-enums -funwind-tables -fstack-protector-strong -Wa,--noexecstack -D_FORTIFY_SOURCE=2 -Wstrict-aliasing=2 -Werror=return-typ
e -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Werror=date-time -Werror=format-security -nostdlibinc -msoft-float -march=armv8-a -mfloat-abi=softfp -mfpu=neon-fp-armv8  -target armv7a-linux-androideabi -Bprebuilts/gcc/
linux-x86/arm/arm-linux-androideabi-4.9/arm-linux-androideabi/bin  -Wsign-promo -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -Wno-thread-safety-negative -Wno-gnu-include-next -fvisibility-inlines-hidden  -std=gnu++17 -mthumb -Os  -fno-rtti 
-Wall -D__ANDROID_API__=29 -D__ANDROID_VNDK__ -fPIC -D_USING_LIBCXX -DANDROID_STRICT   -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=address-of-temporary -Werror=return-type -Wno-tautological-constant-compare -Wno-tautol
ogical-type-limit-compare -Wno-tautological-unsigned-enum-zero-compare -Wno-tautological-unsigned-zero-compare -Wno-c++98-compat-extra-semi -Wno-return-std-move-in-c++11  -MD -MF /run/media/dmitry/1e8e1b30-189e-4254-8ae0-6408e61bf13c/carb
on/out/target/product/mido/obj_arm/SHARED_LIBRARIES/fakelogprint_intermediates/fakelogprint/fakelogprint.d -o /run/media/dmitry/1e8e1b30-189e-4254-8ae0-6408e61bf13c/carbon/out/target/product/mido/obj_arm/SHARED_LIBRARIES/fakelogprint_inte
rmediates/fakelogprint/fakelogprint.o device/xiaomi/mido/libshims/fakelogprint/fakelogprint.cpp"
device/xiaomi/mido/libshims/fakelogprint/fakelogprint.cpp:1:10: fatal error: 'log/log_transport.h' file not found
#include <log/log_transport.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.

Patch-set: 1
Reviewer: Gerrit User 273 <273@4c0b52a2-b090-4331-a190-b288d812d081>
Label: Verified=-1